services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: industrial_iot_kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  kafka-init:
    image: apache/kafka:3.7.0
    container_name: industrial_iot_kafka_init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "
      echo 'Waiting for Kafka to be ready...' &&
      sleep 20 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic sensor-readings --partitions 3 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic maintenance-events --partitions 3 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic operator-events --partitions 3 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic alerts --partitions 3 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic actuator-commands --partitions 3 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic processed-events --partitions 3 --replication-factor 1 &&
      echo 'Kafka topics created successfully.'
      "

  postgres:
    image: postgres:16
    container_name: industrial_iot_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: industrial_iot
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: industrial_iot_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-industrial-iot
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: industrial_iot_fastapi
    depends_on:
      - kafka
      - kafka-init
      - postgres
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_iot
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    volumes:
      - ./app:/app/app

  sql-consumer:
    build:
      context: .
      dockerfile: consumers/Dockerfile
    container_name: industrial_iot_sql_consumer
    depends_on:
      - kafka
      - kafka-init
      - postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SQL_CONSUMER_GROUP_ID: sql-consumer-group
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_iot
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    command: ["python", "-m", "consumers.sql_consumer"]
    profiles:
      - consumers

  alert-consumer:
    build:
      context: .
      dockerfile: consumers/Dockerfile
    container_name: industrial_iot_alert_consumer
    depends_on:
      - kafka
      - kafka-init
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ALERT_CONSUMER_GROUP_ID: alert-consumer-group
    command: ["python", "-m", "consumers.alert_consumer"]
    profiles:
      - consumers

  sensor-simulator:
    build:
      context: .
      dockerfile: producers/Dockerfile
    container_name: industrial_iot_sensor_simulator
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8000
      SIMULATION_INTERVAL_SECONDS: 1
      SIMULATION_EVENT_LIMIT: 50
    command: ["python", "-m", "producers.sensor_simulator"]
    profiles:
      - producers

  maintenance-producer:
    build:
      context: .
      dockerfile: producers/Dockerfile
    container_name: industrial_iot_maintenance_producer
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8000
      MAINTENANCE_INTERVAL_SECONDS: 2
      MAINTENANCE_EVENT_LIMIT: 25
    command: ["python", "-m", "producers.maintenance_event_producer"]
    profiles:
      - producers

  operator-producer:
    build:
      context: .
      dockerfile: producers/Dockerfile
    container_name: industrial_iot_operator_producer
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8000
      OPERATOR_INTERVAL_SECONDS: 2
      OPERATOR_EVENT_LIMIT: 25
    command: ["python", "-m", "producers.operator_input_producer"]
    profiles:
      - producers

volumes:
  kafka_data:
  postgres_data:
